mejores mensajes de error en el signup
omegaup/website-OFMI pull request #38
Opened 2023-12-30 21:33 UTC by Janque

2023-12-30 21:34 UTC, Janque commented
Arregla [Issue 33](https://github.com/omegaup/website-OFMI/issues/33)

2023-12-31 04:21 UTC, Juanito98 requested changes

2023-12-31 04:21 UTC, Juanito98 commented on src/components/signup/index.tsx
> +  }, [error]);
Matalooooo

2023-12-31 04:21 UTC, Juanito98 commented on src/pages/api/user/create.ts
> +      .json({ message: "La contraseña debe tener al menos 8 caractéres" });
Caracteres no lleva acento

2023-12-31 04:21 UTC, Juanito98 commented on src/pages/api/user/create.ts
> -        return res.status(400).json({ message: e.message });
Puedes poner link a la documentación?

https://www.prisma.io/docs/orm/reference/error-reference#p2002

2023-12-31 04:22 UTC, Juanito98 commented
El yarn lock cambió. Haz rebase y vuelve a darle yarn install

2024-01-26 20:02 UTC, Juanito98 approved these changes

2024-02-06 19:27 UTC, Juanito98 approved these changes

2024-08-04 22:43 UTC, merged